const leads = [{
  'Trigger Description': 'The organization is currently evaluating a new mobile security solution. Chad Clemency currently serves as IT Security Administrator',
  'Trigger Type': 'Project',
  'Trigger Date Published': '11/9/2017',
  'Trigger URL': '',
  'Trigger Categories': 'Information Security / Mobility',
  'Employee ID': '560440',
  'Employee First Name': 'Chad',
  'Employee Last Name': 'Clemency',
  'Employee Title': 'IT Security Administrator',
  'Employee Seniority Level': 'Administrator',
  'Employee Reports To': '',
  'Employee Email Address': 'cclemency@dbi.com',
  'Employee Direct Phone': '(610) 943-6151',
  'Company ID': '3523',
  'Company Name': 'David\'s Bridal',
  'Company Primary Industry': 'Retail',
  'Company Revenue': '1627120000',
  'Number of Employees': '12500',
  'HQ Address 1': '1001 Washington Street',
  'HQ Address 2': '',
  'HQ City': 'Conshohocken',
  'HQ State': 'PA',
  'HQ Postal Code': '19428',
  'HQ Country': 'United States',
  id: '4243',
  'Primary Industry': 'Retail',
  'Company Address 1': '1001 Washington Street',
  'Company Address 2': '',
  'Company City': 'Conshohocken',
  'Company State': 'PA',
  'Company Postal Code': '19428',
  'Company Country': 'United States',
  Article: 'The organization is currently evaluating a new mobile security solution. Chad Clemency currently serves as IT Security Administrator',
  'Report Type': 'Project',
  'Date Published': '11/9/2017',
  'Article Link': '',
  Categories: 'Information Security / Mobility',
  'Employee Email': 'cclemency@dbi.com',
  'Employee Phone': '(610) 943-6151',
  SourceFile: 'DiscoverOrg-12.17-1',
  ImportId: '4243',
  CompanyName: 'David\'s Bridal',
  CompanyStateProvince: 'PA',
  CompanyCity: 'Conshohocken',
  CompanyRevenue: '1627120000',
  ContactFirstName: 'Chad',
  ContactLastName: 'Clemency',
  CompanyAddress1: '1001 Washington Street',
  CompanyAddress2: '',
  CompanyCountry: 'United States',
  ContactEmail: 'cclemency@dbi.com',
  Email: 'cclemency@dbi.com',
  Description: 'The organization is currently evaluating a new mobile security solution.',
  CompanyPostalCode: '19428',
  Timezone: 'EST',
  Notes: 'David\'s Bridal - Categories - Information Security / Mobility - Notes: The organization is currently evaluating a new mobile security solution. Chad Clemency currently serves as IT Security Administrator',
  ContactPhone: '610-943-6151',
  CompanyPhone: '',
  IntentToPurchase: 'true',
  SourceDetail: 'RainKing',
  leadIndustries: '["retail"]',
  LeadIndustries: 'retail',
  LeadKeywords: 'security,mobile',
  LeadTitle: 'PA retail company investing in security & mobile',
  ContactPosition: 'other',
  EstimatedOpportunityValue: '',
  Price: '25',
  LeadTiming: '06-18-2018',
  HpKeywords: '[]',
  HpNegatives: '["security"]',
  Keyword: '',
  PrimaryServiceType: '',
  ApplicationType: '',
  ProjectType: '',
  ServiceSpecialization: '',
  KeyWordPriority: '99',
  ProjectStatus: 'In Progress',
  CompanyDomain: 'dbi.com',
  CompanyUrl: 'dbi.com',
  FuelsyRejectReason: ''
},
{
  'Trigger Description': 'The organization has indicated an interest towards IT projects focused on automation solutions for Bloomberg CoreTerminal applications and infrastructure. Thomas Smith currently serves as Senior Software Developer',
  'Trigger Type': 'Project',
  'Trigger Date Published': '11/9/2017',
  'Trigger URL': '',
  'Trigger Categories': 'Application Development / Automation / Infrastructure / IT Projects',
  'Employee ID': '945253',
  'Employee First Name': 'Thomas',
  'Employee Last Name': 'Smith',
  'Employee Title': 'Senior Software Developer',
  'Employee Seniority Level': 'Developer',
  'Employee Reports To': '',
  'Employee Email Address': 'tsmith239@bloomberg.net',
  'Employee Direct Phone': '-260260',
  'Company ID': '3150',
  'Company Name': 'Bloomberg',
  'Company Primary Industry': 'Broadcast Media',
  'Company Revenue': '9300000000',
  'Number of Employees': '19000',
  'HQ Address 1': '731 Lexington Avenue',
  'HQ Address 2': '',
  'HQ City': 'New York',
  'HQ State': 'NY',
  'HQ Postal Code': '10022',
  'HQ Country': 'United States',
  id: '4244',
  'Primary Industry': 'Broadcast Media',
  'Company Address 1': '731 Lexington Avenue',
  'Company Address 2': '',
  'Company City': 'New York',
  'Company State': 'NY',
  'Company Postal Code': '10022',
  'Company Country': 'United States',
  Article: 'The organization has indicated an interest towards IT projects focused on automation solutions for Bloomberg Core Terminal applications and infrastructure. Thomas Smith currently serves as Senior Software Developer',
  'Report Type': 'Project',
  'Date Published': '11/9/2017',
  'Article Link': '',
  Categories: 'Application Development / Automation / Infrastructure / IT Projects',
  'Employee Email': 'tsmith239@bloomberg.net',
  'Employee Phone': '-260260',
  SourceFile: 'DiscoverOrg-12.17-1',
  ImportId: '4244',
  CompanyName: 'Bloomberg',
  CompanyStateProvince: 'NY',
  CompanyCity: 'New York',
  CompanyRevenue: '9300000000',
  ContactFirstName: 'Thomas',
  ContactLastName: 'Smith',
  CompanyAddress1: '731 Lexington Avenue',
  CompanyAddress2: '',
  CompanyCountry: 'United States',
  ContactEmail: 'tsmith239@bloomberg.net',
  Email: 'tsmith239@bloomberg.net',
  Description: 'The organization has indicated an interest towards IT projects focused on automation solutions for company Core Terminal applications and infrastructure.',
  CompanyPostalCode: '10022',
  Timezone: 'EST',
  Notes: 'Bloomberg - Categories - Application Development / Automation / Infrastructure / IT Projects - Notes: The organization has indicated an interest towards IT projects focused on automation solutions for Bloomberg Core Terminal applications and infrastructure. Thomas Smith currently serves as Senior Software Developer',
  ContactPhone: '-260260',
  CompanyPhone: '',
  IntentToPurchase: 'true',
  SourceDetail: 'RainKing',
  leadIndustries: '[]',
  LeadIndustries: 'technology',
  LeadKeywords: 'infrastructure,it projects,automation,terminal,it,development',
  LeadTitle: 'NY technology company investing in infrastructure & it projects',
  ContactPosition: 'other',
  EstimatedOpportunityValue: '',
  Price: '25',
  LeadTiming: '06-18-2018',
  HpKeywords: '[]',
  HpNegatives: '[]',
  Keyword: '',
  PrimaryServiceType: '',
  ApplicationType: '',
  ProjectType: '',
  ServiceSpecialization: '',
  KeyWordPriority: '99',
  ProjectStatus: '',
  CompanyDomain: 'bloomberg.net',
  CompanyUrl: 'bloomberg.net',
  FuelsyRejectReason: ''
},
{
  'Trigger Description': 'The organization has indicated an increased interest in market analytics to support forecasting and strategy development. Kshipra Vairagkar currently serves as Senior Business Intelligence Analyst',
  'Trigger Type': 'Project',
  'Trigger Date Published': '11/3/2017',
  'Trigger URL': '',
  'Trigger Categories': 'Analytics & Insights',
  'Employee ID': '437771',
  'Employee First Name': 'Kshipra',
  'Employee Last Name': 'Vairagkar',
  'Employee Title': 'Senior Business Intelligence Analyst',
  'Employee Seniority Level': 'Analyst',
  'Employee Reports To': '',
  'Employee Email Address': 'kshipra.vairagkar@gartner.com',
  'Employee Direct Phone': '(206) 454-8920',
  'Company ID': '5415',
  'Company Name': 'Gartner',
  'Company Primary Industry': 'IT Services',
  'Company Revenue': '2445000000',
  'Number of Employees': '8813',
  'HQ Address 1': '56 Top Gallant Road',
  'HQ Address 2': '',
  'HQ City': 'Stamford',
  'HQ State': 'CT',
  'HQ Postal Code': '6902',
  'HQ Country': 'United States',
  id: '4245',
  'Primary Industry': 'IT Services',
  'Company Address 1': '56 Top Gallant Road',
  'Company Address 2': '',
  'Company City': 'Stamford',
  'Company State': 'CT',
  'Company Postal Code': '6902',
  'Company Country': 'United States',
  Article: 'The organization has indicated an increased interest in market analytics to support forecasting and strategy development. Kshipra Vairagkar currently serves as Senior Business Intelligence Analyst',
  'Report Type': 'Project',
  'Date Published': '11/3/2017',
  'Article Link': '',
  Categories: 'Analytics & Insights',
  'Employee Email': 'kshipra.vairagkar@gartner.com',
  'Employee Phone': '(206) 454-8920',
  SourceFile: 'DiscoverOrg-12.17-1',
  ImportId: '4245',
  CompanyName: 'Gartner',
  CompanyStateProvince: 'CT',
  CompanyCity: 'Stamford',
  CompanyRevenue: '2445000000',
  ContactFirstName: 'Kshipra',
  ContactLastName: 'Vairagkar',
  CompanyAddress1: '56 Top Gallant Road',
  CompanyAddress2: '',
  CompanyCountry: 'United States',
  ContactEmail: 'kshipra.vairagkar@gartner.com',
  Email: 'kshipra.vairagkar@gartner.com',
  Description: 'The organization has indicated an increased interest in market analytics to support forecasting and strategy development.',
  CompanyPostalCode: '06902',
  Timezone: 'EST',
  Notes: 'Gartner - Categories - Analytics & Insights - Notes: The organization has indicated an increased interest in market analytics to support forecasting and strategy development. Kshipra Vairagkar currently serves as Senior Business Intelligence Analyst',
  ContactPhone: '206-454-8920',
  CompanyPhone: '',
  IntentToPurchase: 'true',
  SourceDetail: 'RainKing',
  leadIndustries: '["it services"]',
  LeadIndustries: 'it services',
  LeadKeywords: 'development,analytics',
  LeadTitle: 'CT it services company investing in development & analytics',
  ContactPosition: 'other',
  EstimatedOpportunityValue: '',
  Price: '25',
  LeadTiming: '06-18-2018',
  HpKeywords: '[]',
  HpNegatives: '[]',
  Keyword: '',
  PrimaryServiceType: '',
  ApplicationType: '',
  ProjectType: '',
  ServiceSpecialization: '',
  KeyWordPriority: '99',
  ProjectStatus: '',
  CompanyDomain: 'gartner.com',
  CompanyUrl: 'gartner.com',
  FuelsyRejectReason: ''
}]

module.exports = leads
